name: codemod_runner
description: A Dart package to run codemods based on migration rules.
version: 0.0.1
repository: https://github.com/juan-campuzano/codemod_runner

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.5.0
  codemod: ^1.0.0
  analyzer: any
  glob: any
  yaml: any
  cli_completion: ^0.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables: 
  codemod_runner:
